// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmknRxPm7QFa-HLeVNhQXl8saxE_KM5_M',
    appId: '1:87953477310:android:d709f80a321da82bcd58ef',
    messagingSenderId: '87953477310',
    projectId: 'fireflut-ad6e0',
    databaseURL: 'https://fireflut-ad6e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fireflut-ad6e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAl86lZtq0lL2vBfUZbbV5djvLpIxuJOs',
    appId: '1:87953477310:ios:d5712143105e2779cd58ef',
    messagingSenderId: '87953477310',
    projectId: 'fireflut-ad6e0',
    databaseURL: 'https://fireflut-ad6e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fireflut-ad6e0.appspot.com',
    androidClientId: '87953477310-dfkb3kfkt5sehordto4ht0946afq36kf.apps.googleusercontent.com',
    iosClientId: '87953477310-gsrhlbns12j3d7mj4m0p09qcc0683cfs.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireflut',
  );
}
